language: node.js
node_js:
  - "stable"
dist: focal
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branches:
      only:
        - main
        - 100849882-Taylor
        - 100851894-Justin
        - 101443253-Amanda
        - 101479568-Ethan
